services:
  # PHP-FPMコンテナ
  app:
    build:
      context: .
    container_name: todays_menu_back
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network

  # Nginxコンテナ
  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8050:80"
    depends_on:
      - app
    networks:
      - app-network

  # MySQLコンテナ
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todays_menu
      MYSQL_USER: user
      MYSQL_PASSWORD: moyashi
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:

