name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.2
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 10022
        script: |
          ls -a
          cd /home/turedureblog.xsrv.jp/todays-menu-back
          git pull origin main
          php artisan migrate --force
          php artisan cache:clear
