name: Deploy to Xserver

on:
  push:
    branches:
      - main  # mainブランチへのプッシュでデプロイを実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.22'
          extensions: mbstring, pdo, mysql

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Deploy to Xserver via SSH
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.XSERVER_HOST }}        # Xserverのホスト名
          username: ${{ secrets.XSERVER_USER }}    # Xserverのユーザー名
          key: ${{ secrets.XSERVER_SSH_KEY }}      # GitHub Secretsに登録したSSHの秘密鍵
          port: 10022
          script: |
            cd ~/turedureblog.xsrv.jp/public_html/todays-menu-back
            git pull origin main
            php artisan migrate --force
            php artisan cache:clear
